- name: Azure Login
  uses: azure/login@v1
  with:
    client-id: ${{ secrets.CLIENT_ID }}
    tenant-id: ${{ secrets.TENANT_ID }}
    subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

- name: Get secret from Key Vault
  uses: azure/get-keyvault-secrets@v1
  with:
    keyvault: 'kv-test-tb'
    secrets: 'sp-secret-name'
  id: getsecret

- name: Use the secret
  run: echo "Le secret est ${{ steps.getsecret.outputs.sp-secret-name }}"
