name: Deploy on Push
on: push
permissions:
  id-token: write

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    environment: Devlopement

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Login to Azure using Service Principal
      run: |
        az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.SECRET_ID }} --tenant ${{ secrets.TENANT_ID }}

    - name: Set Azure Subscription
      run: |
        az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}

    - name: Verify Azure Connection
      run: |
        az account show