name: Deploy on Push
on: push
permissions:
  id-token: write

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    environment: Devlopement

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.SECRET_ID }} --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
          az account show

    - name: Fetch secret from Key Vault
      run: |
        secret_value=$(az keyvault secret show --name "sp-secret-name" --vault-name "kv-test-tb" --query value -o tsv)
        echo "Secret fetched from Key Vault: $secret_value"