name: Build and Deploy a VM

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Devlopement
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
