name: Build and Deploy a VM

on: push

jobs:
  environment: Devlopement
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
    - uses: actions/checkout@v4
    - name: Terraform init
      run: |
        cd test-infra
        terraform init

    - name: Terraform Plan
      run: |
        cd test-infra
        terraform plan