name: Build and Deploy a VM

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    environment: Devlopement
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      working-directory: ./test-infra
      run: |
        terraform init

    - name: Terraform Plan
      working-directory: ./test-infra
      run: |
        terraform plan