name: Build and Deploy a VM

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    environment: Devlopement
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ./test-infra

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      run: |
        terraform init

    - name: Terraform Plan
      run: |
        terraform plan